/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PledgeRouteImport } from './routes/pledge'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as AdoptersRouteImport } from './routes/adopters'
import { Route as IndexRouteImport } from './routes/index'

const PledgeRoute = PledgeRouteImport.update({
  id: '/pledge',
  path: '/pledge',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptersRoute = AdoptersRouteImport.update({
  id: '/adopters',
  path: '/adopters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adopters': typeof AdoptersRoute
  '/codex': typeof CodexRoute
  '/pledge': typeof PledgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adopters': typeof AdoptersRoute
  '/codex': typeof CodexRoute
  '/pledge': typeof PledgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adopters': typeof AdoptersRoute
  '/codex': typeof CodexRoute
  '/pledge': typeof PledgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adopters' | '/codex' | '/pledge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adopters' | '/codex' | '/pledge'
  id: '__root__' | '/' | '/adopters' | '/codex' | '/pledge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdoptersRoute: typeof AdoptersRoute
  CodexRoute: typeof CodexRoute
  PledgeRoute: typeof PledgeRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/pledge': {
      id: '/pledge'
      path: '/pledge'
      fullPath: '/pledge'
      preLoaderRoute: typeof PledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adopters': {
      id: '/adopters'
      path: '/adopters'
      fullPath: '/adopters'
      preLoaderRoute: typeof AdoptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdoptersRoute: AdoptersRoute,
  CodexRoute: CodexRoute,
  PledgeRoute: PledgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
